# Generated by Django 6.0 on 2025-12-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'إجابة', 'verbose_name_plural': 'الإجابات'},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'محاولة', 'verbose_name_plural': 'المحاولات'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'خيار', 'verbose_name_plural': 'الخيارات'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'مشارك', 'verbose_name_plural': 'المشاركون'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name': 'سؤال', 'verbose_name_plural': 'الأسئلة'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'اختبار', 'verbose_name_plural': 'الاختبارات'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.attempt', verbose_name='المحاولة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.choice', verbose_name='الإجابة المختارة'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quiz.participant', verbose_name='المشارك'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='الاختبار'),
        ),
    ]
