# Generated by Django 6.0 on 2025-12-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_options_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='مفتاح الجلسة'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='started_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='User-Agent'),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone_last4',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='آخر 4 أرقام من الجوال'),
        ),
    ]
