# Generated by Django 6.0 on 2025-12-31 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_options_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='وقت الإجابة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.attempt', verbose_name='المحاولة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_late',
            field=models.BooleanField(db_index=True, default=False, verbose_name='متأخر'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_answers', to='quiz.choice', verbose_name='الخيار المختار'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='started_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='وقت بدء السؤال'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='current_index',
            field=models.PositiveIntegerField(default=0, verbose_name='مؤشر السؤال الحالي'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False, verbose_name='منتهٍ'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.participant', verbose_name='المترشح'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='مفتاح الجلسة'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='وكيل المستخدم (User Agent)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False, verbose_name='إجابة صحيحة'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_taken_exam',
            field=models.BooleanField(db_index=True, default=False, verbose_name='أدى الاختبار'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_allowed',
            field=models.BooleanField(db_index=True, default=True, verbose_name='مسموح له بالدخول'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='national_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_last4',
            field=models.CharField(max_length=4, verbose_name='آخر 4 أرقام من الجوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مفعل'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='quiz_answer_attempt_7d1025_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'answered_at'], name='quiz_answer_attempt_135802_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['participant', 'quiz', 'is_finished'], name='quiz_attemp_partici_344838_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['quiz', 'is_finished'], name='quiz_attemp_quiz_id_0536a2_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['started_at'], name='quiz_attemp_started_2e73f7_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question', 'is_correct'], name='quiz_choice_questio_7578ee_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_allowed', 'has_taken_exam'], name='quiz_partic_is_allo_8bc8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['full_name'], name='quiz_partic_full_na_f3b0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='quiz_questi_quiz_id_f13328_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active'], name='quiz_quiz_is_acti_71e796_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uq_answer_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_finished', False)), fields=('participant', 'quiz'), name='uq_attempt_one_open_per_participant_quiz'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='uq_question_quiz_order'),
        ),
    ]
