# Generated by Django 6.0 on 2025-12-31 04:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_answered_at_alter_answer_attempt_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='uq_answer_attempt_question',
        ),
        migrations.RemoveConstraint(
            model_name='attempt',
            name='uq_attempt_one_open_per_participant_quiz',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='uq_question_quiz_order',
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='quiz_answer_attempt_7d1025_idx',
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='quiz_answer_attempt_135802_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='quiz_attemp_partici_344838_idx',
        ),
        migrations.RemoveIndex(
            model_name='choice',
            name='quiz_choice_questio_7578ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='quiz_partic_is_allo_8bc8d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='quiz_partic_full_na_f3b0cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='quiz_questi_quiz_id_f13328_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quiz_quiz_is_acti_71e796_idx',
        ),
        migrations.AddField(
            model_name='participant',
            name='domain',
            field=models.CharField(choices=[('deputy', 'وكيل'), ('counselor', 'موجه طلابي'), ('activity', 'رائد نشاط')], default='deputy', max_length=20, verbose_name='المجال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإجابة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.attempt', verbose_name='المحاولة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='متأخر'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice', verbose_name='الخيار المختار'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت بدء السؤال'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='current_index',
            field=models.IntegerField(default=0, verbose_name='مؤشر السؤال الحالي'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='منتهٍ'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.participant', verbose_name='المترشح'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='session_key',
            field=models.CharField(max_length=200, verbose_name='مفتاح الجلسة'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_agent',
            field=models.CharField(max_length=255, verbose_name='وكيل المستخدم (User Agent)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='إجابة صحيحة'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_taken_exam',
            field=models.BooleanField(default=False, verbose_name='أدى الاختبار'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_allowed',
            field=models.BooleanField(default=True, verbose_name='مسموح له بالدخول'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='national_id',
            field=models.CharField(max_length=20, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_last4',
            field=models.CharField(max_length=10, verbose_name='آخر 4 أرقام من الجوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='مفعل'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt'], name='quiz_answer_attempt_06077e_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='quiz_answer_questio_878891_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['answered_at'], name='quiz_answer_answere_91eef0_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['participant', 'quiz'], name='quiz_attemp_partici_75b035_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['national_id'], name='quiz_partic_nationa_903de6_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['domain'], name='quiz_partic_domain_5d01f0_idx'),
        ),
    ]
