# Generated by Django 6.0 on 2025-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_attempt_session_key_attempt_started_ip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'إجابة', 'verbose_name_plural': 'الإجابات'},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started_at', '-id'], 'verbose_name': 'محاولة', 'verbose_name_plural': 'المحاولات'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id'], 'verbose_name': 'خيار', 'verbose_name_plural': 'الخيارات'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['full_name', 'national_id'], 'verbose_name': 'مشارك', 'verbose_name_plural': 'المشاركون'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-id'], 'verbose_name': 'اختبار', 'verbose_name_plural': 'الاختبارات'},
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['quiz', 'is_finished'], name='quiz_attemp_quiz_id_0536a2_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['participant', 'is_finished'], name='quiz_attemp_partici_42b6f1_idx'),
        ),
    ]
