# Generated by Django 6.0 on 2025-12-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_answer_uq_answer_attempt_question_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='quiz_answer_attempt_06077e_idx',
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='quiz_answer_questio_878891_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='quiz_attemp_quiz_id_0536a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='quiz_attemp_started_2e73f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='quiz_attemp_partici_75b035_idx',
        ),
        migrations.AlterField(
            model_name='participant',
            name='domain',
            field=models.CharField(blank=True, choices=[('deputy', 'وكيل'), ('counselor', 'موجه طلابي'), ('activity', 'رائد نشاط')], max_length=20, null=True, verbose_name='المجال'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='quiz_answer_attempt_7d1025_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['is_finished', 'started_at'], name='quiz_attemp_is_fini_9c88a1_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['participant', 'quiz', 'is_finished'], name='quiz_attemp_partici_344838_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['national_id', 'domain'], name='quiz_partic_nationa_7376ed_idx'),
        ),
    ]
