# Generated by Django 6.0 on 2025-12-25 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_answer_options_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='answer',
            name='uniq_attempt_question',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='quiz_attemp_quiz_id_0536a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='quiz_attemp_partici_42b6f1_idx',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.attempt'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.participant'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_taken_exam',
            field=models.BooleanField(default=False, verbose_name='نفّذ الاختبار'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_allowed',
            field=models.BooleanField(default=True, verbose_name='مسموح'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='السجل'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_last4',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='آخر 4 من الجوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_per_question_seconds',
            field=models.PositiveIntegerField(default=30, verbose_name='زمن السؤال (ث)'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
