# Generated by Django 6.0 on 2025-12-31 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_answer_options_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'إجابة', 'verbose_name_plural': 'الإجابات'},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'محاولة', 'verbose_name_plural': 'المحاولات'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id'], 'verbose_name': 'خيار', 'verbose_name_plural': 'الخيارات'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-id'], 'verbose_name': 'مشارك', 'verbose_name_plural': 'المشاركون'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['quiz_id', 'order', 'id'], 'verbose_name': 'سؤال', 'verbose_name_plural': 'الأسئلة'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-id'], 'verbose_name': 'اختبار', 'verbose_name_plural': 'الاختبارات'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإجابة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.attempt', verbose_name='المحاولة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice', verbose_name='الخيار المختار'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت بدء السؤال'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='current_index',
            field=models.PositiveIntegerField(default=0, verbose_name='مؤشر السؤال الحالي'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='finished_reason',
            field=models.CharField(choices=[('normal', 'طبيعي'), ('timeout', 'تلقائي/انتهاء وقت'), ('forced', 'إغلاق إداري')], db_index=True, default='normal', max_length=20, verbose_name='سبب الإنهاء'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False, verbose_name='منتهية؟'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.participant', verbose_name='المشارك'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='النتيجة'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='مفتاح الجلسة'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='timed_out_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات انتهاء الوقت'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='إجابة صحيحة؟'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(verbose_name='نص الخيار'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='domain',
            field=models.CharField(choices=[('deputy', 'وكيل'), ('counselor', 'موجه طلابي'), ('activity', 'رائد نشاط')], db_index=True, default='deputy', max_length=30, verbose_name='المجال'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=220, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_taken_exam',
            field=models.BooleanField(default=False, verbose_name='أدى الاختبار؟'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_allowed',
            field=models.BooleanField(default=True, verbose_name='مسموح بالدخول؟'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='national_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رقم الهوية/السجل'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_last4',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='آخر 4 أرقام من الجوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتيب السؤال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='نشط؟'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='per_question_seconds',
            field=models.PositiveIntegerField(default=50, verbose_name='ثواني لكل سؤال'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='عنوان الاختبار'),
        ),
    ]
