# Generated by Django 6.0 on 2025-12-31 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_answer_options_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='quiz.choice', verbose_name='الخيار المختار'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.participant', verbose_name='المشارك'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_taken_exam',
            field=models.BooleanField(db_index=True, default=False, verbose_name='أدى الاختبار؟'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_allowed',
            field=models.BooleanField(db_index=True, default=True, verbose_name='مسموح بالدخول؟'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='ans_att_q_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['answered_at'], name='ans_answered_at_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['quiz', '-started_at'], name='att_quiz_started_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['participant', '-started_at'], name='att_part_started_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['is_finished', '-started_at'], name='att_finished_started_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['score'], name='att_score_idx'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question'], name='choice_question_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['domain', 'is_allowed'], name='part_domain_allowed_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['has_taken_exam', 'is_allowed'], name='part_taken_allowed_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='q_quiz_order_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active', '-id'], name='quiz_active_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uq_answer_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_finished', False)), fields=('participant',), name='uq_one_open_attempt_per_participant'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='uq_question_quiz_order'),
        ),
    ]
