# Generated by Django 6.0 on 2025-12-31 17:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('deputy', 'وكيل'), ('counselor', 'موجه طلابي'), ('activity', 'رائد نشاط')], db_index=True, max_length=30, verbose_name='المجال')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='مسموح لهذا المجال؟')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'تسجيل مجال',
                'verbose_name_plural': 'تسجيلات المجالات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExamWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم النافذة')),
                ('domain', models.CharField(choices=[('deputy', 'وكيل'), ('counselor', 'موجه طلابي'), ('activity', 'رائد نشاط')], db_index=True, max_length=30, verbose_name='المجال')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='بداية النافذة')),
                ('ends_at', models.DateTimeField(db_index=True, verbose_name='نهاية النافذة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة؟')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نافذة اختبار',
                'verbose_name_plural': 'نوافذ الاختبارات',
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='answer',
            name='uq_answer_attempt_question',
        ),
        migrations.RemoveConstraint(
            model_name='attempt',
            name='uq_one_open_attempt_per_participant',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='uq_question_quiz_order',
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='ans_att_q_idx',
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='ans_answered_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='att_quiz_started_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='att_part_started_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='att_finished_started_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='att_score_idx',
        ),
        migrations.RemoveIndex(
            model_name='choice',
            name='choice_question_idx',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='part_domain_allowed_idx',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='part_taken_allowed_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='q_quiz_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quiz_active_id_idx',
        ),
        migrations.AddField(
            model_name='attempt',
            name='domain',
            field=models.CharField(choices=[('deputy', 'وكيل'), ('counselor', 'موجه طلابي'), ('activity', 'رائد نشاط')], db_index=True, default='deputy', max_length=30, verbose_name='المجال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت القفل'),
        ),
        migrations.AddField(
            model_name='participant',
            name='locked_domain',
            field=models.CharField(blank=True, choices=[('deputy', 'وكيل'), ('counselor', 'موجه طلابي'), ('activity', 'رائد نشاط')], db_index=True, default='', max_length=30, verbose_name='المجال المقفول عليه'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice', verbose_name='الخيار المختار'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.participant', verbose_name='المشارك'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_taken_exam',
            field=models.BooleanField(default=False, verbose_name='بدأ/أدى اختبار؟'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_allowed',
            field=models.BooleanField(default=True, verbose_name='مسموح بالدخول؟'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='الاختبار'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'order')},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='quiz.participant', verbose_name='المشارك'),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='domain',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('participant', 'domain')},
        ),
    ]
