# Generated by Django 6.0 on 2026-01-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_attempt_participant_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='domain',
            field=models.CharField(choices=[('deputy', 'وكيل'), ('counselor', 'موجّه طلابي'), ('activity', 'رائد نشاط')], db_index=True, max_length=30, verbose_name='المجال'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='domain',
            field=models.CharField(choices=[('deputy', 'وكيل'), ('counselor', 'موجّه طلابي'), ('activity', 'رائد نشاط')], db_index=True, max_length=30, verbose_name='المجال'),
        ),
        migrations.AlterField(
            model_name='examwindow',
            name='domain',
            field=models.CharField(choices=[('deputy', 'وكيل'), ('counselor', 'موجّه طلابي'), ('activity', 'رائد نشاط')], db_index=True, max_length=30, verbose_name='المجال'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='locked_domain',
            field=models.CharField(blank=True, choices=[('deputy', 'وكيل'), ('counselor', 'موجّه طلابي'), ('activity', 'رائد نشاط')], db_index=True, default='', max_length=30, verbose_name='المجال المقفول عليه'),
        ),
    ]
